@startuml
skinparam classAttributeIconSize 0

interface StudentInterface <<interface>> {
    + StudentInterface(void)
    + ~StudentInterface(void)
    + {abstract} unsigned long long int getID()
    + {abstract} string getName()
    + {abstract} string getGPA() = 0;
	+ {abstract} void addGPA(double classGrade) = 0;
    + {abstract} string toString() = 0;

}

interface GPAInterface <<interface>> {
    + GPAInterface(void)
    + ~GPAInterface(void)
    + {abstract} map<unsigned long long int,StudentInterface*> getMap()
    + {abstract} set<StudentInterface*,Comparator> getSet()
    + {abstract} bool importStudents(string mapFileName, string setFileName)
    + {abstract} bool importGrades(string fileName)
    + {abstract} string querySet(string fileName)
	+ {abstract} string queryMap(string fileName)
	+ {abstract} void clear()

}

StudentInterface -right-* GPAInterface 

GPAInterface --* Factory

class Factory {
    + {static} static GPAInterface* getGPA()
}

GPA -right-|> GPAInterface

class GPA {
    - map<unsigned long long int,StudentInterface*> student_map
    - set<StudentInterface*,Comparator> student_set
    - double grade_to_points(string grade)
    - int count_file_lines(string in_file_name)
    + GPA(void)
    + ~GPA(void)
    + map<unsigned long long int,studentinterface*> getmap()
    + set<StudentInterface*,Comparator> getSet()
    + bool importStudents(string mapFileName, string setFileName)
    + bool importGrades(string fileName)
    + string querySet(string fileName)
    + string querySet(string fileName)
    + void clear()
} 

StudentInterface -down-* GPA

Student -right-|> StudentInterface

class Student {
    
    - unsigned long long int id
    - string name
    - string address
    - string phone_number
    - double gpa
    - int num_courses
    - double grade_sum
    + Student(unsigned long long int id, string name,
                 string address, string phone_number, double gpa);
    + ~Student(void);

	+ unsigned long long int getID();

	+ string getName();
	+ string getGPA();
	+ void addGPA(double classGrade);
	+ string toString();
}

@enduml
